### ISSUE TITLE
TypeError: amount.add is not a function

### ISSUE THREAD

**Issue by p3140** [ahmedoubadi/front-running-bot#1]
Hello. First of all great project, thanks for creating it. When i try to run the bot it throws the following error:

TypeError: amount.add is not a function
    at calculate_gas_price (D:\front-running-bot\bot.js:16:44)
    at D:\front-running-bot\bot.js:173:31
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

What i am missing ?

**Comment by ahmedoubadi** [comment]
issue has been fixed, thank you for reporting
