### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by m4hdi1995** [ahmedoubadi/front-running-bot#5]
Hello, as I can see there is a blacklist for the tokens we don't want to front run, isn't it better to had a whitelist? because there are a lot of tokens with high liquidity, I think it's better for the user to choose and whitelist tokens he or she wanted to front run. also please correct me if I'm wrong or mistaken. thank you.

**Comment by dani-s-92** [comment]
> Hello, as I can see there is a blacklist for the tokens we don't want to front run, isn't it better to had a whitelist? because there are a lot of tokens with high liquidity, I think it's better for the user to choose and whitelist tokens he or she wanted to front run. also please correct me if I'm wrong or mistaken. thank you.

ANd one more question -> Why is value for selling set to 99? Does it mean, sell all bought coints? Oder do I have to change the number?

**Comment by ahmedoubadi** [comment]
> Hello, as I can see there is a blacklist for the tokens we don't want to front run, isn't it better to had a whitelist? because there are a lot of tokens with high liquidity, I think it's better for the user to choose and whitelist tokens he or she wanted to front run. also please correct me if I'm wrong or mistaken. thank you.

yes ofcourse it's better to add a whitelist of tokens that you want to frontrun, because there is a lot of shity coin that you can't sell after buying

**Comment by ahmedoubadi** [comment]
> > Hello, as I can see there is a blacklist for the tokens we don't want to front run, isn't it better to had a whitelist? because there are a lot of tokens with high liquidity, I think it's better for the user to choose and whitelist tokens he or she wanted to front run. also please correct me if I'm wrong or mistaken. thank you.
> 
> ANd one more question -> Why is value for selling set to 99? Does it mean, sell all bought coints? Oder do I have to change the number?

the value is 99 that's mean sell 99% of your token, if you set it to 100 sometimes it throws an error if the token is too volatile

**Comment by fantamoja** [comment]
Hello, great job. Thank you ever so much for sharing. If it's not too much to ask, could you share your whitelist code I see how you approached it?  Thank you

**Comment by ahmedoubadi** [comment]
we do have a professional frontrunning bot that has all the feature like whitelist and blacklist and a lot of other feature, if you're interested you can check our website [FastlyBot](https://fastlybot.com)
