### ISSUE TITLE
Advice:  put the transaction in the same block

### ISSUE THREAD

**Issue by TroubleSeven** [ahmedoubadi/front-running-bot#6]
the sellToken function always approve first, so it's always come out that buy & sell in different blocks. 
Can we put both of the transaction in the same block ?

**Comment by ahmedoubadi** [comment]
that's depend on the full node you're connected to, it will put the two transactions in the same block if it's a high perfomante node

**Comment by z1017371914** [comment]
> 
how to get the full node? cheap and faster.

**Comment by ahmedoubadi** [comment]
> > 
> 
> how to get the full node? cheap and faster.

You can use fastlynode, they do offer cheap and fast nodes, or you can run your own node
